theme: jekyll-theme-slate
title: PCA Project
description: Hi, this is my very first school project in python so please, don't be too harsh! This work was realized by Nicolas Darbois (@FellowNico) and me.
plugins:
  - jekyll-mentions
